'use client'

import { Video, Sparkles, Play, Download, Clock, Layers, Book, Users, Wand2, Loader2, Globe } from 'lucide-react'
import { useAura } from '@/context/AuraContext'
import { useState, useEffect } from 'react'

export default function VideoStudio() {
  const { documents, activeAgent, renderJobs, addRenderJob, addTelemetryLog } = useAura()
  const [isSynthesizing, setIsSynthesizing] = useState(false)
  const [htmlCode, setHtmlCode] = useState('<!-- Awaiting AI Generation -->\n<div class="hyperframe-scene" data-duration="30s">\n  <heygen-avatar agent="aura-x" />\n</div>')

  const [studioMode, setStudioMode] = useState<'knowledge' | 'outreach' | 'batch'>('knowledge')
  const [synthesisGoal, setSynthesisGoal] = useState('')
  const [targetName, setTargetName] = useState('')
  const [targetCompany, setTargetCompany] = useState('')

  const [isExporting, setIsExporting] = useState(false)
  const [videoJobs, setVideoJobs] = useState<any[]>([])

  // Load real video jobs
  useState(() => {
     fetch('/api/video/jobs')
       .then(res => res.json())
       .then(data => { if (Array.isArray(data)) setVideoJobs(data); })
  })

  // Poll for status updates
  useEffect(() => {
    const interval = setInterval(() => {
       const processingJobs = videoJobs.filter(j => j.status === 'PROCESSING');
       if (processingJobs.length > 0) {
          processingJobs.forEach(async (job) => {
             try {
                const res = await fetch(`/api/video/status?id=${job.id}`);
                const data = await res.json();
                if (data.success && data.job.status !== 'PROCESSING') {
                   setVideoJobs(prev => prev.map(j => j.id === job.id ? data.job : j));
                   if (data.job.status === 'COMPLETED') {
                      addTelemetryLog({ source: 'VIDEO_ENGINE', trace: `Render completed: ${job.title}`, status: 'SUCCESS' });
                   }
                }
             } catch (e) {}
          });
       }
    }, 5000);
    return () => clearInterval(interval);
  }, [videoJobs]);

  const handleSynthesize = async () => {
    if (studioMode === 'knowledge' && !documents.length) {
       alert("No knowledge base documents found. Please sync your KB first.");
       return;
    }
    setIsSynthesizing(true)
    addTelemetryLog({ source: 'STUDIO', trace: 'Synthesizing HyperFrame composition...', status: 'PROCESSING' })
    
    try {
      const res = await fetch('/api/studio', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          mode: studioMode,
          documentId: documents.length > 0 ? documents[0].id : null,
          documentTitle: documents.length > 0 ? documents[0].title : null,
          targetProfile: studioMode === 'outreach' ? { name: targetName || 'John Doe', company: targetCompany || 'Acme Corp' } : null,
          agentId: activeAgent?.id,
          empathy: activeAgent?.empathy,
          instruction: synthesisGoal
        })
      });
      
      const data = await res.json();
      
      if (res.ok) {
        setHtmlCode(data.html);
        addTelemetryLog({ source: 'STUDIO', trace: 'Composition ready for export', status: 'SUCCESS' });
      } else {
        throw new Error(data.error);
      }
    } catch (err) {
      console.error("Synthesis failed", err);
      addTelemetryLog({ source: 'STUDIO', trace: 'Synthesis failed.', status: 'ERROR' });
    } finally {
      setIsSynthesizing(false)
    }
  }

  const handleExportVideo = async () => {
     if (htmlCode.includes('Awaiting AI Generation')) return;
     setIsExporting(true);
     addTelemetryLog({ source: 'VIDEO_ENGINE', trace: 'Initializing MP4 render job via HeyGen API...', status: 'PROCESSING' });

     try {
       const res = await fetch('/api/video/generate', {
         method: 'POST',
         headers: { 'Content-Type': 'application/json' },
         body: JSON.stringify({
           title: studioMode === 'outreach' ? `Outreach: ${targetName}` : 'Knowledge Base Explainer',
           script: synthesisGoal || "Welcome to our video generated by Aura.",
           avatarId: activeAgent?.avatarId,
           voiceId: activeAgent?.voiceId
         })
       });

       const data = await res.json();
       if (data.success) {
          setVideoJobs([data.job, ...videoJobs]);
          addTelemetryLog({ source: 'VIDEO_ENGINE', trace: `Job submitted to farm: ${data.job.id}`, status: 'SUCCESS' });
       } else {
          alert(data.error);
       }
     } catch (e) {
       console.error(e);
       addTelemetryLog({ source: 'VIDEO_ENGINE', trace: 'Render submission failed.', status: 'ERROR' });
     } finally {
       setIsExporting(false);
     }
  }
  return (
    <div className="p-10 max-w-[1600px] mx-auto space-y-12">
      <header className="space-y-1">
        <h1 className="text-3xl font-bold text-white tracking-tighter uppercase">Video <span className="text-zinc-500 font-medium">Studio</span></h1>
        <div className="flex items-center gap-2 text-[10px] font-bold text-zinc-500 uppercase tracking-[0.4em]">
           Powered by HeyGen <span className="text-cyan-500">HyperFrames</span>
        </div>
      </header>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        
        {/* Production Lab */}
        <div className="lg:col-span-5 space-y-8">
           <div className="glass-card p-8 space-y-8">
              <div className="flex items-center justify-between border-b border-white/5 pb-4">
                 <div className="flex items-center gap-3">
                    <Sparkles size={16} className="text-cyan-400" />
                    <h3 className="text-[11px] font-bold text-zinc-400 uppercase tracking-[0.2em]">Production Lab</h3>
                 </div>
                 <div className="flex gap-1">
                    <div className="w-1 h-1 rounded-full bg-cyan-500 shadow-[0_0_5px_cyan]" />
                 </div>
              </div>
              
              <div className="space-y-6">
                 {/* Mode Selector */}
                 <div className="grid grid-cols-3 gap-3">
                    <button 
                       onClick={() => setStudioMode('knowledge')}
                       className={`p-4 rounded-2xl font-bold text-[9px] uppercase tracking-widest flex flex-col items-center gap-2 transition-all ${studioMode === 'knowledge' ? 'bg-white text-black' : 'bg-white/5 border border-white/5 text-zinc-500 hover:border-white/20 hover:text-white'}`}
                    >
                       <Book size={16} />
                       Knowledge Base
                    </button>
                    <button 
                       onClick={() => setStudioMode('outreach')}
                       className={`p-4 rounded-2xl font-bold text-[9px] uppercase tracking-widest flex flex-col items-center gap-2 transition-all ${studioMode === 'outreach' ? 'bg-white text-black' : 'bg-white/5 border border-white/5 text-zinc-500 hover:border-white/20 hover:text-white'}`}
                    >
                       <Users size={16} />
                       Single Outreach
                    </button>
                    <button 
                       onClick={() => setStudioMode('batch')}
                       className={`p-4 rounded-2xl font-bold text-[9px] uppercase tracking-widest flex flex-col items-center gap-2 transition-all ${studioMode === 'batch' ? 'bg-white text-black' : 'bg-white/5 border border-white/5 text-zinc-500 hover:border-white/20 hover:text-white'}`}
                    >
                       <Layers size={16} />
                       Batch CSV
                    </button>
                 </div>

                 {studioMode === 'knowledge' && (
                   <div className="space-y-4">
                      <div className="space-y-2">
                         <label className="text-[9px] font-bold text-zinc-600 uppercase tracking-widest">Select Knowledge Source</label>
                         <select className="w-full bg-black/50 border border-white/5 rounded-xl px-4 py-4 text-xs text-white appearance-none focus:outline-none">
                           {documents.map(doc => <option key={doc.id}>{doc.title}</option>)}
                           {documents.length === 0 && <option>No Documents Available in KB</option>}
                         </select>
                      </div>

                      <div className="space-y-2">
                         <label className="text-[9px] font-bold text-zinc-600 uppercase tracking-widest">Synthesis Goal</label>
                         <textarea 
                            rows={4}
                            value={synthesisGoal}
                            onChange={(e) => setSynthesisGoal(e.target.value)}
                            placeholder="e.g. Summarize the 'Safety Protocol' into a 1-minute explainer for new employees."
                            className="w-full bg-black/50 border border-white/5 rounded-xl p-4 text-xs text-white placeholder:text-zinc-700 focus:outline-none focus:border-cyan-500/50 resize-none transition-all"
                         />
                      </div>
                   </div>
                 )}
                 
                 {studioMode === 'outreach' && (
                   <div className="space-y-4">
                      <div className="grid grid-cols-2 gap-4">
                         <div className="space-y-2">
                            <label className="text-[9px] font-bold text-zinc-600 uppercase tracking-widest">Target Name</label>
                            <input 
                               type="text" 
                               value={targetName}
                               onChange={(e) => setTargetName(e.target.value)}
                               placeholder="John Doe" 
                               className="w-full bg-black/50 border border-white/5 rounded-xl px-4 py-4 text-xs text-white placeholder:text-zinc-700 focus:outline-none focus:border-cyan-500/50" 
                            />
                         </div>
                         <div className="space-y-2">
                            <label className="text-[9px] font-bold text-zinc-600 uppercase tracking-widest">Target Company</label>
                            <input 
                               type="text" 
                               value={targetCompany}
                               onChange={(e) => setTargetCompany(e.target.value)}
                               placeholder="Acme Corp" 
                               className="w-full bg-black/50 border border-white/5 rounded-xl px-4 py-4 text-xs text-white placeholder:text-zinc-700 focus:outline-none focus:border-cyan-500/50" 
                            />
                         </div>
                      </div>
                      <div className="space-y-2">
                         <label className="text-[9px] font-bold text-zinc-600 uppercase tracking-widest">Outreach Pitch</label>
                         <textarea 
                            rows={3}
                            value={synthesisGoal}
                            onChange={(e) => setSynthesisGoal(e.target.value)}
                            placeholder="e.g. Highlight our new API infrastructure and how it solves their scaling issues."
                            className="w-full bg-black/50 border border-white/5 rounded-xl p-4 text-xs text-white placeholder:text-zinc-700 focus:outline-none focus:border-cyan-500/50 resize-none transition-all"
                         />
                      </div>
                   </div>
                 )}

                 {studioMode === 'batch' && (
                   <div className="space-y-4">
                      <div className="space-y-2">
                         <label className="text-[9px] font-bold text-zinc-600 uppercase tracking-widest">Upload Targets (CSV)</label>
                         <div className="border border-dashed border-white/10 rounded-xl p-8 flex flex-col items-center justify-center space-y-4 bg-white/[0.02]">
                            <Download size={24} className="text-zinc-600" />
                            <div className="text-center">
                               <p className="text-xs text-white">Drop your .csv file here</p>
                               <p className="text-[9px] text-zinc-500 uppercase tracking-widest mt-1">Columns: Name, Company, LinkedIn URL</p>
                            </div>
                            <input type="file" accept=".csv" className="hidden" id="csv-upload" />
                            <label htmlFor="csv-upload" className="px-6 py-3 bg-white/10 hover:bg-white/20 transition-colors rounded-lg text-[10px] font-bold uppercase tracking-widest text-white cursor-pointer">
                               Browse Files
                            </label>
                         </div>
                      </div>
                   </div>
                 )}

                 <button 
                    onClick={handleSynthesize}
                    className="w-full py-5 bg-cyan-500 text-black font-black text-[10px] uppercase tracking-[0.3em] rounded-2xl hover:bg-cyan-400 transition-all shadow-[0_15px_30px_-10px_rgba(6,182,212,0.4)] flex justify-center items-center gap-2"
                 >
                    {isSynthesizing ? <Loader2 size={14} className="animate-spin" /> : <Wand2 size={14} />} 
                    {isSynthesizing ? 'Synthesizing...' : 'Synthesize Video'}
                 </button>
              </div>
           </div>

           <div className="glass-card p-8 space-y-6">
              <div className="flex items-center gap-3 border-b border-white/5 pb-4">
                 <Layers size={16} className="text-zinc-500" />
                 <h3 className="text-[11px] font-bold text-zinc-400 uppercase tracking-[0.2em]">Generated HTML/CSS</h3>
              </div>
              <div className="h-48 bg-black/80 rounded-xl border border-white/5 p-4 overflow-y-auto font-mono text-[9px] text-zinc-500 whitespace-pre">
                 {htmlCode}
              </div>
           </div>
        </div>

        {/* Renderer Preview */}
        <div className="lg:col-span-7 space-y-8 flex flex-col">
           <div className="flex-1 glass-card p-4 rounded-3xl flex flex-col">
              <div className="flex justify-between items-center px-4 py-2 border-b border-white/5 mb-4">
                 <h3 className="text-[11px] font-bold text-zinc-500 uppercase tracking-[0.2em]">HyperFrames Renderer</h3>
                 <div className="flex items-center gap-2 text-[9px] font-bold text-zinc-500 uppercase tracking-widest">
                    <div className="w-1.5 h-1.5 rounded-full bg-amber-500 animate-pulse" /> Engine Idle
                 </div>
              </div>
              
              <div className="flex-1 bg-black/50 rounded-2xl border border-white/5 flex items-center justify-center relative overflow-hidden group">
                 {/* Empty State */}
                 <div className="text-center space-y-4">
                    <div className="w-16 h-16 rounded-full bg-white/5 flex items-center justify-center mx-auto text-zinc-700 group-hover:text-cyan-500 transition-colors">
                       <Video size={24} />
                    </div>
                    <p className="text-[10px] font-bold text-zinc-600 uppercase tracking-widest">No Composition Loaded</p>
                 </div>
              </div>

               <div className="mt-4 px-4 py-3 bg-white/5 rounded-xl flex justify-between items-center">
                  <div className="space-y-1">
                     <p className="text-[10px] font-bold text-zinc-300 uppercase tracking-widest">Render Queue</p>
                     <p className="text-[9px] font-mono text-zinc-600">{videoJobs.filter((j: any) => j.status === 'PROCESSING').length} Active Jobs</p>
                  </div>
                  <button 
                     onClick={handleExportVideo}
                     disabled={isExporting || htmlCode.includes('Awaiting AI Generation')}
                     className={`px-6 py-2 font-bold text-[9px] uppercase tracking-widest rounded-lg flex items-center gap-2 transition-all
                        ${isExporting || htmlCode.includes('Awaiting AI Generation') 
                           ? 'bg-zinc-800 text-zinc-500 cursor-not-allowed' 
                           : 'bg-cyan-500 text-black hover:bg-cyan-400 shadow-[0_0_15px_rgba(6,182,212,0.3)]'
                        }`}
                  >
                     {isExporting ? <Loader2 size={12} className="animate-spin" /> : <Video size={12} />}
                     {isExporting ? 'Submitting...' : 'Render MP4'}
                  </button>
               </div>
            </div>

             {/* Recent Renders */}
            <div className="glass-card rounded-2xl overflow-hidden">
               <div className="px-6 py-4 border-b border-white/5 bg-white/[0.02]">
                  <h3 className="text-[10px] font-black text-zinc-500 uppercase tracking-[0.3em]">Recent Exports</h3>
               </div>
               <div className="divide-y divide-white/5">
                  {videoJobs.map((job: any) => (
                     <ExportRow key={job.id} job={job} />
                  ))}
                  {videoJobs.length === 0 && (
                     <div className="p-8 text-center text-[10px] font-bold text-zinc-600 uppercase tracking-widest">
                        No Export History
                     </div>
                  )}
               </div>
            </div>
         </div>
      </div>
    </div>
  )
}

function ExportRow({ job }: { job: any }) {
  const isProcessing = job.status === 'PROCESSING';
  const isFailed = job.status === 'FAILED';

  return (
    <div className="px-6 py-4 flex items-center justify-between hover:bg-white/[0.02] transition-colors group">
       <div className="flex items-center gap-4">
          <div className={`w-10 h-10 rounded-lg border flex items-center justify-center transition-colors
             ${isProcessing ? 'bg-amber-500/10 border-amber-500/20 text-amber-500' : 
               isFailed ? 'bg-red-500/10 border-red-500/20 text-red-500' : 
               'bg-zinc-900 border-white/5 text-zinc-600 group-hover:text-cyan-400'}`}
          >
             {isProcessing ? <Loader2 size={16} className="animate-spin" /> : <Video size={16} />}
          </div>
          <div>
             <p className="text-[11px] font-bold text-zinc-300">{job.title}</p>
             <p className="text-[9px] font-mono text-zinc-600 flex items-center gap-2 mt-1">
                <Clock size={10} /> {job.duration} • {new Date(job.createdAt).toLocaleDateString()}
             </p>
          </div>
       </div>
       <div className="flex gap-2 items-center">
          {isProcessing && <span className="text-[9px] font-bold text-amber-500 uppercase tracking-widest px-3">Rendering...</span>}
          {isFailed && <span className="text-[9px] font-bold text-red-500 uppercase tracking-widest px-3">Failed</span>}
          
          {job.funnelUrl && !isProcessing && !isFailed && (
             <a href={job.funnelUrl} target="_blank" className="p-2 rounded-lg border border-white/5 hover:bg-cyan-500 hover:text-black transition-colors" title="Open Funnel">
                <Globe size={14} className="text-zinc-400 hover:text-black" />
             </a>
          )}
          {job.videoUrl && (
             <a href={job.videoUrl} target="_blank" className="p-2 rounded-lg border border-cyan-500/30 hover:bg-cyan-500 hover:text-black text-cyan-400 transition-colors" title="Download MP4">
                <Download size={14} className="inherit" />
             </a>
          )}
       </div>
    </div>
  )
}
